apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: fluent-bit
  template:
    metadata:
      labels:
        name: fluent-bit
    spec:
      serviceAccountName: fluent-bit   # Should be annotated for IRSA if using CloudWatch
      containers:
        - name: fluent-bit
          image: amazon/aws-for-fluent-bit:2.27.0
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/log/containers
            - name: config
              mountPath: /fluent-bit/etc/                     # Mount configmap containing fluent-bit.conf
            - name: parsers
              mountPath: /fluent-bit/etc/parsers.conf         # ✅ Mount the shared parser file
              subPath: parsers.conf
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
          securityContext:
            privileged: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/log/containers
        - name: config
          configMap:
            name: fluent-bit-config
        - name: parsers
          configMap:
            name: fluent-bit-parsers                         # ✅ Refers to the shared parser ConfigMap
