apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  progressDeadlineSeconds: 60
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: 443370713928.dkr.ecr.us-east-1.amazonaws.com/my-vote-worker:latest
          livenessProbe:
            exec:
              command: [ "sleep", "5" ]
            initialDelaySeconds: 15
            periodSeconds: 30
