apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: fluent-bit
  template:
    metadata:
      labels:
        name: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.8.12     # ✅ Same image as elasticsearch version
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/log/containers
            - name: config
              mountPath: /fluent-bit/etc/
            - name: parsers
              mountPath: /fluent-bit/etc/parsers.conf   # ✅ Use shared parser
              subPath: parsers.conf
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          securityContext:
            privileged: true
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/log/containers
        - name: config
          configMap:
            name: fluent-bit-config
        - name: parsers
          configMap:
            name: fluent-bit-parsers
