apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: fluent-bit
  template:
    metadata:
      labels:
        name: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.8.12     # 🔁 Open source version compatible with EFK
          volumeMounts:
            - name: varlog
              mountPath: /var/log             # Read logs from host
            - name: containers
              mountPath: /var/log/containers  # K8s container logs
            - name: config
              mountPath: /fluent-bit/etc/     # Fluent Bit config
            - name: parsers
              mountPath: /fluent-bit/etc/parsers.conf   # ✅ Mount shared CRI parser
              subPath: parsers.conf
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          securityContext:
            privileged: true                  # Needed to access host paths
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/log/containers
        - name: config
          configMap:
            name: fluent-bit-config
        - name: parsers
          configMap:
            name: fluent-bit-parsers         # ✅ Shared parser for all environments
