apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: monitoring
data:
  alerting_rules.yml: |
    groups:
    - name: probe-alerts
      rules:
      - alert: PodNotReady
        expr: kube_pod_container_status_ready == 0
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Pod not ready"
          description: "Pod {{ $labels.pod }} on {{ $labels.node }} is not ready for more than 30s."

      - alert: ContainerFrequentRestarts
        expr: increase(kube_pod_container_status_restarts_total[1m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Container restarting frequently"
          description: "{{ $labels.container }} in pod {{ $labels.pod }} is restarting repeatedly."
