apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: kube-system
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File /fluent-bit/parsers/parsers.conf      # ✅ Updated to full path inside mounted folder

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            cri
        Tag               kube.*
        Refresh_Interval  5
        Skip_Long_Lines   On
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     10MB
        Buffer_Chunk_Size 512KB
        Buffer_Max_Size   5MB

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Merge_Log           On
        Keep_Log            Off

    [OUTPUT]
        Name                es
        Match               *
        Host                elasticsearch.logging.svc
        Port                9200
        Index               fluentbit
        Type                _doc
        Logstash_Format     On
        Retry_Limit         False
