apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: fluent-bit
  template:
    metadata:
      labels:
        name: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:1.8.12
          volumeMounts:
            - name: varlog
              mountPath: /var/log                          # System logs
            - name: containers
              mountPath: /var/log/containers               # K8s logs
            - name: config
              mountPath: /fluent-bit/etc/                  # Mount configMap with fluent-bit.conf
            - name: parsers
              mountPath: /fluent-bit/etc/parsers.conf      # ✅ Mount parser directory
              subPath: parsers.conf
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
          securityContext:
            privileged: true                               # Required for hostPath access
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/log/containers
        - name: config
          configMap:
            name: fluent-bit-config
        - name: parsers
          configMap:
            name: fluent-bit-parsers                       # ✅ Reference to shared parser configMap
