apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-parsers
  namespace: kube-system
data:
  parsers.conf: |
    [PARSER]
    Name        cri
    Format      regex
    Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[F|P]) (?<log>.*)$
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
