# === ServiceAccount to bind Fluent Bit pod identity ===
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/FluentBitEKSRole  # 🔁 CHANGE: Replace with your actual IRSA IAM Role ARN

---
# === ClusterRole with read-only access to pods and namespaces ===
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
    - pods               # Needed to attach pod metadata
    - namespaces         # For enrichment
  verbs:
    - get
    - list
    - watch

---
# === Bind the ClusterRole to the Fluent Bit ServiceAccount ===
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: kube-system
